mcp_connect "db" "npx -y @modelcontextprotocol/server-sqlite customers.db"
mcp_connect "maps" "npx -y @modelcontextprotocol/server-google-maps"
>=> mcp_agent "db" "get all customer names, companies, addresses, cities and states from the customers table"
>=> mcp_agent "maps" "geocode the first customer address: 233 W 49th St, New York, NY"
>=> ask "Given these 10 customers across the US, suggest an optimal 3-day sales road trip route grouping nearby cities together"
>=> maps_trip "Sales Road Trip"
